const express=require('express')
const bodyParser=require('body-parser')
const app=express()
const adminRoutes=require('./routes/admin')
const messageRoutes=require('./routes/message')
const loginRoutes=require('./routes/login')
app.use(bodyParser.urlencoded({extended:false}))
app.use('/admin',adminRoutes)
app.use('/message',messageRoutes)
app.use('/login',loginRoutes)
app.use('/',(req, res, next)=>{
    res.send('<h1>HOME PAGE</h1>')
})
app.use((req, res, next)=>{
    res.status(404).send('<h1>Page Not Found</h1>')
})
app.listen(3000)